spring:
    profiles:
        active: default
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://mysqldb.zbjdl.in:3306/zbjdl_oa?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
        username: root
        password: wK=QwJmR<592
        validationQuery: SELECT 1 FROM DUAL

# REDIS (RedisProperties)
    redis:
        host: redis.zbjdl.in
        port: 6378
        pool:
            max-idle: 300 # pool settings ...
            max-active: 600
            max-wait: 1000
#mybatis:
#    config: classpath:mybatisConfig.xml


endpoints:
    jmx:
        enabled: false 

server:
    contextPath: /oa-wx
    port: 9025
    admin-boss:
        url: http://testboss.zbjdl.net:8080/admin-boss

logging:
    level:
        com:
            zbjdl:
                utils:
                    query: DEBUG

registry-address: registry.zbjdl.in:2181
service-group: zbjdl-service-group
service-version: 1.0.0

zbjdl:
    dubbo:
        app: oa-wx
        registry_address: registry.zbjdl.in:2181

---

spring:
    profiles: development
    
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/test?useUnicode=true&characterEncoding=utf8
        username: root
        password: root


server:
    port: 8093

---
spring:
    profiles: production

    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://mysqldb.zbjdl.in:3306/zbjdl_oa?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
        validation-query: select 1 from dual
        test-on-borrow: true
        username: root
        password: m&tpI4boxy7H

server:
    contextPath: /oa-wx
    port: 9025
